name: SourcePawn CI

on: [push]

jobs:
  ci:
    name: SourcePawn CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SourceMod
        uses: KatsuteTF/Workflows/actions/setup-sourcepawn@main

      - name: mkdir include
        shell: bash
        run: mkdir -p addons/sourcemod/include

      - name: Compile Plugin
        run: spcomp -i addons/sourcemod/include TF100.sp