name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SourceMod
        uses: KatsuteTF/Workflows/actions/setup-sourcepawn@main

      - name: mkdir include
        shell: bash
        run: mkdir -p addons/sourcemod/include

      - name: Compile Plugin
        run: spcomp -i addons/sourcemod/include TF100.sp

      - name: Prepare Files
        run: |-
          mkdir addons/sourcemod/scripting
          mv TF100.smx addons/sourcemod/scripting
          mkdir addons/sourcemod/gamedata
          mv tf2.100.txt addons/sourcemod/gamedata

      - name: Deploy to GitHub Releases
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: "addons/*;item_whitelist.txt"
          repo-token: ${{ secrets.GITHUB_TOKEN }}